export * from './gql.query.client.generated.type';
export * from './gql.query.tag.generated.type';
export * from './gql.fragment.contentParts.generated.type';
export * from './gql.fragment.lead.generated.type';
export * from './gql.fragment.views.generated.type';
export * from './gql.fragment.adress.generated.type';
export * from './gql.fragment.phone.generated.type';
export * from './querySearch.generated.type';
export * from './gql.query.article.generated.type';
