import { FRAGMENT_COVER } from './gql.cover.type';

export type FRAGMENT_CONTENTPARTS_TYPE = FRAGMENT_CONTENTPART_TYPE[]


export type FRAGMENT_CONTENTPART_TYPE = {
  __typename: string,
  id: string
} & FRAGMENT_CONTENTPART_TXT_TYPE & FRAGMENT_CONTENTPART_QUOTE_TYPE & FRAGMENT_CONTENTPART_MEDIA_TYPE

export type FRAGMENT_CONTENTPART_TXT_TYPE = {
  txt?: string
}

export type FRAGMENT_CONTENTPART_QUOTE_TYPE = {
  quote?: string
}

export type FRAGMENT_CONTENTPART_MEDIA_TYPE = {
  media?: FRAGMENT_COVER
}



